---
deployment:
      tasks:
        - export DEPLOYPATH=/home/u1608313/public_html  # Add /<app_folder> if required
        - /bin/cp index.html $DEPLOYPATH                 #Copy specific file to destination from root
        - /bin/cp /css/lighbox.css $DEPLOYPATH   #copy specific file from source sub folder 
        - /bin/cp /css/my_style.css $DEPLOYPATH   #copy specific file from source sub folder 
        - /bin/cp /css/testimoni.css $DEPLOYPATH   #copy specific file from source sub folder 
        - /bin/cp /js/lighbox.js $DEPLOYPATH   #copy specific file from source sub folder 
        - /bin/cp /js/my_js.js $DEPLOYPATH   #copy specific file from source sub folder 
        - /bin/cp /js/testimoni.js $DEPLOYPATH   #copy specific file from source sub folder 
        - /bin/cp -R img * $DEPLOYPATH         
        - /bin/cp/img -R galery * $DEPLOYPATH         
        - /bin/cp -R fonts * $DEPLOYPATH